


/*CURSORES*/

SELECT * FROM B_LOCALIDAD;

DECLARE
	CURSOR LOCALI IS
		SELECT * FROM B_LOCALIDAD;
	
	CURSOR C_CLIENTES (ID_LOCAL NUMBER) IS
		SELECT bp.NOMBRE, bp.APELLIDO, SUM(bv.MONTO_TOTAL) 
			FROM B_PERSONAS bp JOIN B_VENTAS bv
			ON bv.ID_CLIENTE = bp.ID
			JOIN B_LOCALIDAD bl
			ON bl.ID = bp.ID_LOCALIDAD
			WHERE bp.ES_CLIENTE = 'S'
			AND bl.ID = ID_LOCAL
			GROUP BY bp.NOMBRE, bp.APELLIDO;

BEGIN
	FOR A IN LOCALI LOOP	/*NO HACER OPEN NI FETCH USANDO FOR LOOP*/
	DBMS_OUTPUT.PUT_LINE('LOCALIDAD:'||A.NOMBRE);
		FOR R_CLI IN C_CLIENTES LOOP
			DBMS_OUTPUT.PUT_LINE('CLIENTE: '||R_CLI.NOMBRE||' '||' VENTAS: '||R_CLI.TOTAL);
		END LOOP;
	END LOOP;
END;


/*FUNCIONES Y PROCEDIMIENTOS*/
CREATE OR REPLACE FUNCTION F_CALCULAR_SALDO()

SELECT * FROM B_CUENTAS bc;